### PR TITLE
new DataSets

### LINKED ISSUE #28: Add more data sets to data set table
Right now, only _medium-voltage grid districts_ appears in the [data set table](https://github.com/gplssm/egon-website/blob/dev/_data/openego_data.yml). Decide on which data sets should be added and add them.

Ideas from @gplssm

- osmTGmod transmission grid model
- ...

### PR DESCRIPTION
**Pull request by KathiEsterl**
Fix #28 

Die Datasets, die Ilka aufgelistet hat, habe ich eingefügt. 
Schaut euch bitte gern besonders die Beschreibungen nochmal an. 
Die Lizenzen habe ich wie im Beispiel übernommen, die sollten ja gleich sein, oder?

### CODE REVIEW

**Comment by IlkaCu** [comment]
Die Lizenzen müsstest du noch einmal in den Metadaten der Tabellen auf der OEP nachprüfen: https://openenergy-platform.org/dataedit/view/grid

**Comment by IlkaCu** [comment]
I suggest the following descriptions: 

Demand/Supply: Renewable and conventional powerplants and electricity demand in a high spatial resolution 
eTraGo model: Input tables for HV powerflow calculations with our eTraGo tool 

osmTGmod: Grid model generated with the osmTGmod tool 
(@KathiEsterl: use osmTGmod instead of egoTGmod)

**Comment by KathiEsterl** [comment]
> I suggest the following descriptions:
> 
> Demand/Supply: Renewable and conventional powerplants and electricity demand in a high spatial resolution
> eTraGo model: Input tables for HV powerflow calculations with our eTraGo tool
> 
> osmTGmod: Grid model generated with the osmTGmod tool
> (@KathiEsterl: use osmTGmod instead of egoTGmod)

I added the licences for each of the datasets and also changed the descriptions to your suggestions. 
What do you mean by this: _use osmTGmod instead of egoTGmod_ ?

Im going to push my changes tomorrow, I got some merge-troubles and have to fix them first...

**Comment by IlkaCu** [comment]
Sorry, this wasn't well articulated. I just meant, that I would like you to replace 'Data processed by egoTGmod' by 'Data processed by osmTGmod'.

**Comment by KathiEsterl** [comment]
Now I updated the openego_data.yml-file with the right licences and descriptions and (after some troubles) were finally able to push my changes. I hope I did it the right way, I am still a beginner with github and had some problems with merging.
As there is a lot more information about licenses now, probably the file to construct the table has to be changed too, but I dont know how to do that. If you want me to change it myself, tell me and I will try to find out! 
Just tell me, if something is wrong and/or how to improve my work, I am happy about proposals and help to get better with all that stuff!

**Pull request merged**
