### PR TITLE
Feature/hp

### LINKED ISSUE #10: Design start page (home)
Content of the start page is defined in [index.md](https://github.com/gplssm/egon-website/blob/dev/pages/pages-root-folder/index.md).

Layout elements of the page according to sketches, oru phone call discussion and your personal preferences :sweat_smile:

### PR DESCRIPTION
**Pull request by bmlancien**
fix #10

### CODE REVIEW

**Comment by bmlancien** [comment]
> No line breaks in super wide view (3840 px)

Do you mean for example that the text for open_ego stays in one line on very large screens? If that's the case, I would not recommend it, because that would be really hard to read. I could instead increase the width of the text box to let the text take more space.

> We decided to have no "contact page"
We should remove the contact button below the project description
should we leave button to link to tools+data page or shall we simply remove it?

I removed the contact button, but I think we should leave the tools+data button since this is the main action we want our users to take (see the tools + data)

> Our tasks: We have a title for each task: Planning Tool, Sector Coupling, Modeling and Complexity, Open Data / Open Source. Would be possible to add these somehow? Or would you advice to leave each task without a title?

No, I think this is a good idea to have a title for each task, because the user doesn't have to read the whole texts to understand what the tasks are. I just didn't know before how the tasks would look like, that's why I didn't include them

> In HP_hero_img_v2_for_web.svg, in the center, there many lines crossing. Do you think it could be an improvement when the gray area has a little bit more opacity and maybe a little bit lighter color? Just an idea. If you're happy and you dont't have an indea for improving it, leave it as it is!

I get your point. I added a new version with a darker background for the central element. I actually prefer it that way, because it stands out and the blue/black colors remember the logo colors. 

About the workshop section, will there be a link to something?

**Comment by gplssm** [comment]
>> No line breaks in super wide view (3840 px)
> Do you mean for example that the text for open_ego stays in one line on very large screens? If that's the case, I would not recommend it, because that would be really hard to read. I could instead increase the width of the text box to let the text take more space.
I forgot to insert the screenshot
Bildschirmfoto_2020-04-24_10-08-40

**Comment by bmlancien** [comment]
Ah, that's still the same issue than yesterday. What I don't understand is that I thought I had fixed it. Did you clear the cache? Which browser are you using?

Bildschirmfoto vom 2020-04-24 12-10-55

**Comment by gplssm** [comment]
> > We decided to have no "contact page"
> > We should remove the contact button below the project description
> > should we leave button to link to tools+data page or shall we simply remove it?
> 
> I removed the contact button, but I think we should leave the tools+data button since this is the main action we want our users to take (see the tools + data)

:+1: 

> > Our tasks: We have a title for each task: Planning Tool, Sector Coupling, Modeling and Complexity, Open Data / Open Source. Would be possible to add these somehow? Or would you advice to leave each task without a title?
> 
> No, I think this is a good idea to have a title for each task, because the user doesn't have to read the whole texts to understand what the tasks are. I just didn't know before how the tasks would look like, that's why I didn't include them

:+1: 

> > In HP_hero_img_v2_for_web.svg, in the center, there many lines crossing. Do you think it could be an improvement when the gray area has a little bit more opacity and maybe a little bit lighter color? Just an idea. If you're happy and you dont't have an indea for improving it, leave it as it is!
> 
> I get your point. I added a new version with a darker background for the central element. I actually prefer it that way, because it stands out and the blue/black colors remember the logo colors.

I like it that way :clap: 

> About the workshop section, will there be a link to something?

Not yet. Right now, it's more like announcing there will be workshops. I think when we start preparing the workshops, we'll add a page with information and results after the workshop. We should a a link then.

**Comment by gplssm** [comment]
> Ah, that's still the same issue than yesterday. What I don't understand is that I thought I had fixed it. Did you clear the cache? Which browser are you using?
> 
> Bildschirmfoto vom 2020-04-24 12-10-55

Maybe I didn't pull? Now, it works perfectly. My fault :see_no_evil:

From my side, we're ready for merging :tada: 
Do you do the merge? Let me now, if I should do it

**Comment by bmlancien** [comment]
Ah, I'm relieved :)

I can do the merge!

**Pull request merged**
