### PR TITLE
Nav + Footer

### LINKED ISSUE #6: Style navbar
Customize layout of the navbar as you like :smile: 
Personally, I would like to have small version of the logo right next to "eGo^n".

Entries of the navbar are defined in [navigation.yml](https://github.com/gplssm/egon-website/blob/dev/_data/navigation.ymly). How the information is processed, see [here](https://github.com/gplssm/egon-website/blob/dev/_includes/_navigation.html).

### LINKED ISSUE #8: Style footer
Customize layout of the footer. Content is already included in [the file for the footer](https://github.com/gplssm/egon-website/blob/dev/_includes/_footer.html).

Is a copyright remark required?

### LINKED ISSUE #16: Insert eGo^n logo next to "eGon" in navbar
This might be related to #15

### PR DESCRIPTION
**Pull request by bmlancien**
Set top-nav and footer colors to blue and changed layout.

fix #6 fix #8 fix #16

### CODE REVIEW

**Comment by bmlancien** [comment]
@gplssm I tried to add an empty legal page and a link into the footer, but didn't work, so I just removed it. We probabbly need a legal page, right?

**Comment by gplssm** [comment]
> @gplssm I tried to add an empty legal page and a link into the footer, but didn't work, so I just removed it. We probabbly need a legal page, right?

I've discussed this with Matthias. We agreed to have only one page called "Imprint" which contains contact information and a disclaimer including data protection information. Hence, I renamed "Impress" in the footer to "Imprint" and removed "Contact".

**Comment by gplssm** [comment]
I've edited the footer
- Copyright information replaced by CC-BY-4.0 licensing information
- Move to same row as credits
- Remove contact link from navbar as it was removed from footer

**Comment by bmlancien** [comment]
@gplssm I changed the footer. What do you think?

**Comment by gplssm** [comment]
I would merge it right into dev. But, as I created a PR to this feature branch #20, I would like to merge this first (or the newly created branch which inserts the logo into the navbar).

**Pull request merged**
