### PR TITLE
Fix/#16 logo in navbar

### LINKED ISSUE #16: Insert eGo^n logo next to "eGon" in navbar
This might be related to #15

### PR DESCRIPTION
**Pull request by gplssm**
fix #16 

Included the logo without project below in navbar.

@bmlancien one issue remains: when eGon (with the logo next to it) is highlighted, the logo partially disappears because the background switches to the same color as the ring of the logo. Two quick ideas to resolve this

1. Use an inverted version of the logo in case it is highlighted
2. Buffer the dark blue areas with a little bit of white color

What do you think?

### CODE REVIEW

**Comment by bmlancien** [comment]
I would rather change the logo for the navigation, i.e. make "egon" as part of the image and not as HTML. I would then remove the blue background so the blue logo would always keep a white background. It's quite standard to have the logo different from the rest of the navigation.

Nav

One more thing: the navigation on medium size screens is not working properly on that branch (between 640 and 1024px width). The hamburger menu is not there anymore. I'm not sure where the problem is right now. I could branch from feature/nav (which seems to work properly) and add the new logo.

**Comment by gplssm** [comment]
> I would rather change the logo for the navigation, i.e. make "egon" as part of the image and not as HTML. I would then remove the blue background so the blue logo would always keep a white background. It's quite standard to have the logo different from the rest of the navigation.
> 
> Nav
> 
> One more thing: the navigation on medium size screens is not working properly on that branch (between 640 and 1024px width). The hamburger menu is not there anymore. I'm not sure where the problem is right now. I could branch from feature/nav (which seems to work properly) and add the new logo.

Thanks for the explanation what's the standard of doing it!

Thanks for checking medium size devices! I just jumped between small and large.

If it's easier to branch again from `feature/nav` feel free. Based on the changes I've made above, I gues, you can see where the changes have to take place.

**Comment by bmlancien** [comment]
> If it's easier to branch again from feature/nav feel free. Based on the changes I've made above, I gues, you can see where the changes have to take place.

Ok, i will do it that way then.

**Comment by bmlancien** [comment]
@gplssm I added the new logo to the top bar in the `feature/nav` branch. I couldn't remove the text next to the logo though. Could you do that? Also, the logo is the only anchor to the homepage now, as it is quite common to have just the logo and not an extra "home" link as a text. I.e. only "Tools+Data", "Publications" and "Partners" are left in the dropdwon nav.

Other thing: I thought I had changed the `title` and `description` meta tags in `_config.yml`, but I can't see the changes. I probably missed something.

0 0 0 0_4000_(iPhone 6_7_8)

**Comment by gplssm** [comment]
> @gplssm I added the new logo to the top bar in the feature/nav branch. I couldn't remove the text next to the logo though. Could you do that?

I hope, so :) I'll have a look on it in 15 mins.

> Other thing: I thought I had changed the title and description meta tags in _config.yml, but I can't see the changes. I probably missed something.

Changes in `_config.yml ` only take effect after running Jekyll again. So, you have to run the `docker run ... ` command again.

**Comment by gplssm** [comment]
> @gplssm I added the new logo to the top bar in the feature/nav branch. I couldn't remove the text next to the logo though. Could you do that?

Fixed in 39d985a423c2b198fe12b493e16f61d0c31ed0e9 (branch feature/nav)

**Comment by bmlancien** [comment]
> Changes in _config.yml only take effect after running Jekyll again. So, you have to run the docker run ... command again.

Ah ok! Good to know :)

**Comment by gplssm** [comment]
Are we ready here?

**Comment by gplssm** [comment]
I've compared this branch to feature/nav and noticed feature/nav #13 is more up-to-date. Explanation: you have inserted the new logo including text on the right side in feature/nav. Which resolves #16 

So, I would merge #13 into dev and close this one. Any objections?

**Comment by bmlancien** [comment]
Yes, feature/nav is up-to-date!

**Comment by gplssm** [comment]
#13 already closed #16

**Pull request closed without merging**
