### PR TITLE
Feature/tools data

### LINKED ISSUE #11: Design page "Tools & Data"
Content is sketched by [tools+data.md](https://github.com/gplssm/egon-website/blob/dev/pages/tools%2Bdata.md) which includes [_tools.html](https://github.com/gplssm/egon-website/blob/dev/_includes/_tools.html) and [openego_data.html](https://github.com/gplssm/egon-website/blob/dev/_includes/openego_data.html). This is general a smart way using Jekyll and rather more using data files (`.yml`) and liquid.

### Tools

- Tool chain image will be replaced (without boarder)
- As example ding0 is already included as simple card. The length of description is represenative
- Buttons on the bottom indicate intended links. Guess you can make them look nicer easily :smile: 
- Liquid is use to loop through all tools defned in [tools.yml](https://github.com/gplssm/egon-website/blob/dev/_data/tools.yml)

### Data

- Again Liquid is used to loop over datasets
- Idea: use [pictograms of license features](https://meta.wikimedia.org/wiki/Open_Content_-_A_Practical_Guide_to_Using_Creative_Commons_Licences/The_Creative_Commons_licencing_scheme#/media/File:Open_Content_A_Practical_Guide_to_Using_Creative_Commons_Licences_web-28.png) (could be defined in `.yml`)

### Linking to OEDB

Somehow nicely link to the OEDB including the logo

### PR DESCRIPTION
**Pull request by bmlancien**
fix #11 

I didn't know how to add icons to "Our Tools" section (#11). Is that possible directly in a YAML file?

### CODE REVIEW

**Comment by gplssm** [comment]
I've added an icon via the `.yml` file. Could you please enhance the appearance of it?

I took the GitHub icon from [here](https://www.iconfinder.com/icons/1632512/circle_github_round_icon_icon) and is licensed under CC-BY-SA-3.0. So, it requires attribution. Do you have GitHub and ReadTheDocs icons that do not require attribution?

**Comment by bmlancien** [comment]
> I took the GitHub icon from here and is licensed under CC-BY-SA-3.0. So, it requires attribution. Do you have GitHub and ReadTheDocs icons that do not require attribution?

For GitHub I simply used that one: https://github.com/logos
I can't see any mention of attribution requirements, do you?

About Read the Docs, I can see that attribution is mandatory. So I will have to find another solution...

If it's not possible to find any logo without attribution required, would you be okay with having just text instead?

**Comment by bmlancien** [comment]
> Could you please
> 
> let the icons below each tool appear nicer
> Take a look on the alignment of tools (they are all listed vertically)
> Check if it still looks good for you after inserting real content

I changed a few things. Please have a look!

**Comment by gplssm** [comment]
> > I took the GitHub icon from here and is licensed under CC-BY-SA-3.0. So, it requires attribution. Do you have GitHub and ReadTheDocs icons that do not require attribution?
> 
> For GitHub I simply used that one: https://github.com/logos
> I can't see any mention of attribution requirements, do you?
> 
> About Read the Docs, I can see that attribution is mandatory. So I will have to find another solution...
> 
> If it's not possible to find any logo without attribution required, would you be okay with having just text instead?

I would like to use an icon too for RTD. I see two options
1. Use the official  [RTD icon](https://read-the-docs-guidelines.readthedocs-hosted.com/branding.html) and reference to source and license, for example, in imprint (or newly to be created legal page)
2. Use an icon from the noun project, where the RLI has access, download and use rights without need for backreference (if Matthias downloads it with a special account). For example this icon [here](https://thenounproject.com/search/?q=book&i=3324965)

I somehow prefer option 2, because it seems to involve less work. If you agree, I would ask Matthias to download the icon for us.

**Comment by gplssm** [comment]
> > Could you please
> > let the icons below each tool appear nicer
> > Take a look on the alignment of tools (they are all listed vertically)
> > Check if it still looks good for you after inserting real content
> 
> I changed a few things. Please have a look!
Looks cool! I've noticed just one thing: the GitHub+RTD links for eGo appear on top of column 3 instead of at the bottom of column 2

grafik

We should add a text above "Our Tools" to separate a bit more. But that's up to us and we can use text formatting from the other paragraphs

**Comment by bmlancien** [comment]
> I would like to use an icon too for RTD. I see two options
> 
> Use the official RTD icon and reference to source and license, for example, in imprint (or newly to be created legal page)
> Use an icon from the noun project, where the RLI has access, download and use rights without need for backreference (if Matthias downloads it with a special account). For example this icon here

I also have access to the Noun Project with his account, so option 2 would be no problem.

>  the GitHub+RTD links for eGo appear on top of column 3 instead of at the bottom of column 2

Good that you saw it. On Chrome there was no bug.

> We should add a text above "Our Tools" to separate a bit more.

You mean between the title "Our tools" and the tools below?

**Comment by gplssm** [comment]
>> We should add a text above "Our Tools" to separate a bit more.
>You mean between the title "Our tools" and the tools below?
Right.

**Comment by bmlancien** [comment]
> We should add a text above "Our Tools" to separate a bit more.

I added dummy text

**Comment by gplssm** [comment]
I'll merge it when #13 is merged

**Pull request merged**
